### ISSUE TITLE
Failing to install yaourt (to be used for snapd)

### ISSUE THREAD

**Issue by n3rd4i** [bilguun0203/ArchLinuxFS#1]
Installing yaourt using this [tutorial](https://www.ostechnix.com/install-yaourt-arch-linux/) fails with the following error: 
```
==> Entering fakeroot environment...
fakeroot, while creating message channels: Function not implemented
This may be due to a lack of SYSV IPC support.
fakeroot: error while starting the `faked' daemon.
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
```

Steps to reproduce:
1. follow guide from: "2. Install Yaourt using AUR"
2. execute step: `makepkg -si`

The point of having the above, is to install [snapd](https://docs.snapcraft.io/core/install-arch-linux)

Any help on the matter will be appreciated.

**Comment by bilguun0203** [comment]
When you running this command `$ sudo pacman -S --needed base-devel git wget yajl` did you removed `fakeroot-tcp`.
If you did you will get that error, because `fakeroot` doesn't work properly on Windows

**Comment by bilguun0203** [comment]
Ignore `fakeroot` and don't remove `fakeroot-tcp`.
